/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_ndkjnidemo_JniUtils */

#ifndef _Included_demo_ndkjnidemo_JniUtils
#define _Included_demo_ndkjnidemo_JniUtils

JNIEXPORT void JNICALL Java_demo_ndkjnidemo_JniUtils_setBitmap(JNIEnv *env, jclass type,
                                                               jobject src);

JNIEXPORT void JNICALL Java_demo_ndkjnidemo_JniUtils_render(JNIEnv *env, jclass type, jobject dst);

JNIEXPORT void JNICALL Java_demo_ndkjnidemo_JniUtils_drop(JNIEnv *env, jclass type, jint x, jint y, jint height);

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_ndkjnidemo_JniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_demo_ndkjnidemo_JniUtils_getStringFormC(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
